# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ant/Programming/RixinSDL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ant/Programming/RixinSDL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ant/Programming/RixinSDL/CMakeFiles /home/ant/Programming/RixinSDL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ant/Programming/RixinSDL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RixinSDL

# Build rule for target.
RixinSDL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RixinSDL
.PHONY : RixinSDL

# fast build rule for target.
RixinSDL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/build
.PHONY : RixinSDL/fast

src/EventDispatcher.o: src/EventDispatcher.cpp.o
.PHONY : src/EventDispatcher.o

# target to build an object file
src/EventDispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/EventDispatcher.cpp.o
.PHONY : src/EventDispatcher.cpp.o

src/EventDispatcher.i: src/EventDispatcher.cpp.i
.PHONY : src/EventDispatcher.i

# target to preprocess a source file
src/EventDispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/EventDispatcher.cpp.i
.PHONY : src/EventDispatcher.cpp.i

src/EventDispatcher.s: src/EventDispatcher.cpp.s
.PHONY : src/EventDispatcher.s

# target to generate assembly for a file
src/EventDispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/EventDispatcher.cpp.s
.PHONY : src/EventDispatcher.cpp.s

src/Image.o: src/Image.cpp.o
.PHONY : src/Image.o

# target to build an object file
src/Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/Image.cpp.o
.PHONY : src/Image.cpp.o

src/Image.i: src/Image.cpp.i
.PHONY : src/Image.i

# target to preprocess a source file
src/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/Image.cpp.i
.PHONY : src/Image.cpp.i

src/Image.s: src/Image.cpp.s
.PHONY : src/Image.s

# target to generate assembly for a file
src/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/Image.cpp.s
.PHONY : src/Image.cpp.s

src/RixinSDL.o: src/RixinSDL.cpp.o
.PHONY : src/RixinSDL.o

# target to build an object file
src/RixinSDL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/RixinSDL.cpp.o
.PHONY : src/RixinSDL.cpp.o

src/RixinSDL.i: src/RixinSDL.cpp.i
.PHONY : src/RixinSDL.i

# target to preprocess a source file
src/RixinSDL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/RixinSDL.cpp.i
.PHONY : src/RixinSDL.cpp.i

src/RixinSDL.s: src/RixinSDL.cpp.s
.PHONY : src/RixinSDL.s

# target to generate assembly for a file
src/RixinSDL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/RixinSDL.cpp.s
.PHONY : src/RixinSDL.cpp.s

src/TextureRepository.o: src/TextureRepository.cpp.o
.PHONY : src/TextureRepository.o

# target to build an object file
src/TextureRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/TextureRepository.cpp.o
.PHONY : src/TextureRepository.cpp.o

src/TextureRepository.i: src/TextureRepository.cpp.i
.PHONY : src/TextureRepository.i

# target to preprocess a source file
src/TextureRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/TextureRepository.cpp.i
.PHONY : src/TextureRepository.cpp.i

src/TextureRepository.s: src/TextureRepository.cpp.s
.PHONY : src/TextureRepository.s

# target to generate assembly for a file
src/TextureRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/TextureRepository.cpp.s
.PHONY : src/TextureRepository.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/WindowManager.o: src/WindowManager.cpp.o
.PHONY : src/WindowManager.o

# target to build an object file
src/WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/WindowManager.cpp.o
.PHONY : src/WindowManager.cpp.o

src/WindowManager.i: src/WindowManager.cpp.i
.PHONY : src/WindowManager.i

# target to preprocess a source file
src/WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/WindowManager.cpp.i
.PHONY : src/WindowManager.cpp.i

src/WindowManager.s: src/WindowManager.cpp.s
.PHONY : src/WindowManager.s

# target to generate assembly for a file
src/WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/WindowManager.cpp.s
.PHONY : src/WindowManager.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RixinSDL.dir/build.make CMakeFiles/RixinSDL.dir/src/glad.c.s
.PHONY : src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RixinSDL"
	@echo "... src/EventDispatcher.o"
	@echo "... src/EventDispatcher.i"
	@echo "... src/EventDispatcher.s"
	@echo "... src/Image.o"
	@echo "... src/Image.i"
	@echo "... src/Image.s"
	@echo "... src/RixinSDL.o"
	@echo "... src/RixinSDL.i"
	@echo "... src/RixinSDL.s"
	@echo "... src/TextureRepository.o"
	@echo "... src/TextureRepository.i"
	@echo "... src/TextureRepository.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/WindowManager.o"
	@echo "... src/WindowManager.i"
	@echo "... src/WindowManager.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

